Repository netguru-code-college/vol3-orange, pull requests merged in 2018-08, with the labels that each got.

#31 Dependent destroy
  app/models/place.rb
  app/models/trip.rb
  app/models/user.rb
  app/views/trips/_form.html.erb
  app/views/trips/new.html.erb
Labels: Ready for review

#36 Little refactoring
  Gemfile
  Gemfile.lock
  app/views/trips/_form.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/routes.rb
Labels: Ready for review

#42 Add google login
  Gemfile
  Gemfile.lock
  app/controllers/users/omniauth_callbacks_controller.rb
  app/models/user.rb
  config/initializers/devise.rb
  config/routes.rb
Labels: Ready for review

#43 Add button
  .gitignore
  app/assets/images/btn_google_signin_light_pressed_web.png
  app/controllers/users/omniauth_callbacks_controller.rb
  app/views/devise/shared/_links.html.erb
Labels: Ready for review

#48 Forms
  Gemfile
  Gemfile.lock
  app/models/transport.rb
  app/models/trip.rb
  app/views/attractions/_form.html.erb
  app/views/attractions/edit.html.erb
  app/views/attractions/new.html.erb
  app/views/hotels/_form.html.erb
  app/views/hotels/edit.html.erb
  app/views/hotels/new.html.erb
  app/views/places/_form.html.erb
  app/views/places/edit.html.erb
  app/views/places/new.html.erb
  app/views/transports/_form.html.erb
  app/views/transports/edit.html.erb
  app/views/transports/new.html.erb
  app/views/trips/_form.html.erb
  app/views/trips/edit.html.erb
  app/views/trips/new.html.erb
Labels: Ready for review

#49 Delete obsolete views, controller actions and routes
  app/controllers/hotels_controller.rb
  app/controllers/places_controller.rb
  app/controllers/transports_controller.rb
  app/views/places/edit.html.erb
  app/views/places/index.html.erb
  app/views/places/show.html.erb
  app/views/transports/_form.html.erb
  app/views/transports/edit.html.erb
  config/routes.rb
Labels: Ready for review, Review done

#53 trip show edits
  app/assets/stylesheets/trips.scss
  app/views/trips/show.html.erb
Labels: Review done
